### PR TITLE
fix(DateField): Reset field segments when model value is undefined

### LINKED ISSUE #1426: [Bug]: Setting date picker's model value to `undefined` doesn't reset field's segments
### Environment

```bash
Radix Vue version: 1.9.9
```

### Link to minimal reproduction

<details>

```
<template>
    <div class="p-8">
        <div class="flex flex-col gap-2">
            <Label
                class="text-white text-sm"
                for="date-field"
            >
                Birthday
            </Label>
            <DatePickerRoot
                id="date-field"
                v-model="modelValue"
            >
                <DatePickerField
                    v-slot="{ segments }"
                    class="flex w-40 select-none items-center justify-between rounded-lg border border-transparent bg-white p-1 text-center data-[invalid]:border-red-500"
                >
                    <div class="flex items-center">
                        <template
                            v-for="item in segments"
                            :key="item.part"
                        >
                            <DatePickerInput
                                v-if="item.part === 'literal'"
                                :part="item.part"
                            >
                                {{ item.value }}
                            </DatePickerInput>
                            <DatePickerInput
                                v-else
                                :part="item.part"
                                class="rounded-md p-0.5 data-[placeholder]:text-gray-400 focus:shadow-[0_0_0_2px] focus:shadow-black focus:outline-none "
                            >
                                {{ item.value }}
                            </DatePickerInput>
                        </template>
                    </div>

                    <DatePickerTrigger class="rounded-md p-1 text-xl focus:shadow-[0_0_0_2px] focus:shadow-black">
                        calicon
                    </DatePickerTrigger>
                </DatePickerField>

                <DatePickerContent
                    :side-offset="4"
                    class="will-change-[transform,opacity]] rounded-xl bg-white shadow-[0_10px_38px_-10px_hsla(206,22%,7%,.35),0_10px_20px_-15px_hsla(206,22%,7%,.2)]"
                >
                    <DatePickerArrow class="fill-white" />
                    <DatePickerCalendar
                        v-slot="{ weekDays, grid }"
                        class="p-4"
                    >
                        <DatePickerHeader class="flex items-center justify-between">
                            <DatePickerPrev
                                class="inline-flex size-8 cursor-pointer items-center justify-center rounded-[9px] bg-transparent text-black hover:bg-black hover:text-white focus:shadow-[0_0_0_2px] focus:shadow-black active:scale-95 active:transition-all"
                            >
                                {{ '<' }}
                            </DatePickerPrev>

                            <DatePickerHeading class="font-medium text-black" />
                            <DatePickerNext
                                class="inline-flex size-8 cursor-pointer items-center justify-center rounded-[9px] bg-transparent text-black hover:bg-black hover:text-white focus:shadow-[0_0_0_2px] focus:shadow-black active:scale-95 active:transition-all"
                            >
                                >
                            </DatePickerNext>
                        </DatePickerHeader>
                        <div
                            class="flex flex-col space-y-4 pt-4 sm:flex-row sm:space-x-4 sm:space-y-0"
                        >
                            <DatePickerGrid
                                v-for="month in grid"
                                :key="month.value.toString()"
                                class="w-full border-collapse select-none space-y-1"
                            >
                                <DatePickerGridHead>
                                    <DatePickerGridRow class="mb-1 flex w-full justify-between">
                                        <DatePickerHeadCell
                                            v-for="day in weekDays"
                                            :key="day"
                                            class="w-8 rounded-md text-xs"
                                        >
                                            {{ day }}
                                        </DatePickerHeadCell>
                                    </DatePickerGridRow>
                                </DatePickerGridHead>
                                <DatePickerGridBody>
                                    <DatePickerGridRow
                                        v-for="(weekDates, index) in month.rows"
                                        :key="`weekDate-${index}`"
                                        class="flex w-full"
                                    >
                                        <DatePickerCell
                                            v-for="weekDate in weekDates"
                                            :key="weekDate.toString()"
                                            :date="weekDate"
                                        >
                                            <DatePickerCellTrigger
                                                :day="weekDate"
                                                :month="month.value"
                                                class="relative flex size-8 items-center justify-center whitespace-nowrap rounded-[9px] border border-transparent bg-transparent font-normal text-black outline-none text-sm before:absolute before:top-[5px] before:hidden before:size-1 before:rounded-full before:bg-white data-[unavailable]:pointer-events-none data-[selected]:bg-black data-[selected]:font-medium data-[disabled]:text-black/30 data-[selected]:text-white data-[unavailable]:text-black/30 data-[unavailable]:line-through data-[today]:before:block data-[selected]:before:bg-white hover:border-black focus:shadow-[0_0_0_2px] focus:shadow-black"
                                            />
                                        </DatePickerCell>
                                    </DatePickerGridRow>
                                </DatePickerGridBody>
                            </DatePickerGrid>
                        </div>
                    </DatePickerCalendar>
                </DatePickerContent>
            </DatePickerRoot>
        </div>

        <p class="text-white">
            Model value: {{ modelValue }}
        </p>

        <button
            class="text-white"
            @click="modelValue = undefined"
        >
            RESET
        </button>
    </div>
</template>

<script lang="ts" setup>
const modelValue = ref(undefined)
</script>
```

</details>

### Steps to reproduce

1. Enter a date into the date picker field.
2. Change the binded model value to `undefined`.
3. Observe how date picker field's segments remain unchanged.

### Describe the bug

https://github.com/user-attachments/assets/3129cb8a-3b18-4990-8b17-3ebbc13da167

### Expected behavior

Date picker field's segments are reset when model value changes to `undefined`.

### Context & Screenshots (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by epr3**
Closes #1426.

### CODE REVIEW

**Review by zernonia — APPROVED** [review]
LGTM!

**Comment by DamianGlowala** [comment]
@epr3 I've installed `https://pkg.pr.new/unovue/radix-vue/radix-vue@98ee034` to test this PR with attached component in the reproduction and sadly, I can't see any difference. Segments remain. LMK if you can reproduce too with my example.

File: packages/radix-vue/src/DateField/DateFieldRoot.vue [hunk 1]
```diff
@@ -199,7 +199,7 @@ watch([modelValue, locale], ([_modelValue]) => {
   if (_modelValue !== undefined) {
     segmentValues.value = { ...syncSegmentValues({ value: _modelValue, formatter }) }
   }
-  else if (Object.values(segmentValues.value).every(value => value === null)) {
+  else if (Object.values(segmentValues.value).every(value => value === null) || modelValue === undefined) {
```
Comment (DamianGlowala) [inline packages/radix-vue/src/DateField/DateFieldRoot.vue:202]: Also, for consistency, this should probably be `_modelValue` rather than `modelValue`?
