### PR TITLE
fix(TagsInputRoot): avoid mutating modelValue directly

### LINKED ISSUE #1508: [Bug]: TagsInput Direct Mutation of Readonly Computed Values
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/zuvlqjfj?file=src%2FApp.vue

### Steps to reproduce

Attempt to delete a tag.

### Describe the bug

- Tags cannot be deleted
- The TagsInputRoot tries to mutate the modelValue directly instead of emitting a new value and letting the parent component handle the mutation

Vue Warning in the console:
```
[Vue warn] Delete operation on key "1" failed: target is readonly.
[Vue warn] Set operation on key "length" failed: target is readonly.
```

### Expected behavior

The TagsInputRoot emits `update:model-value` with the new value instead of trying to mutate the value directly.

### Context & Screenshots (if applicable)

In `TagsInput/TagsInputRoot.vue`, the component directly mutates the `modelValue` using array mutation methods:

```
modelValue.value.splice(index, 1) // For deletion
modelValue.value.push(payload) // For addition
```

### Suggested Fix
Replace direct mutations with non-mutating array operations:
```
// For deletion
modelValue.value = modelValue.value.toSpliced(index, 1)
// For addition
modelValue.value = [...modelValue.value, payload]
```

### Additional Context
This issue affects any usage where the v-model is bound to a readonly computed property, which is a common pattern when working with derived state.

### PR DESCRIPTION
**Pull request by ploca14**
fix #1508

### CODE REVIEW

File: packages/radix-vue/src/TagsInput/TagsInputRoot.vue [hunk 1]
```diff
@@ -142,7 +142,7 @@ provideTagsInputRootContext({
   },
   onRemoveValue: (index) => {
     if (index !== -1)
-      modelValue.value.splice(index, 1)
+      modelValue.value = modelValue.value.toSpliced(index, 1)
```
Comment (zernonia) [inline packages/radix-vue/src/TagsInput/TagsInputRoot.vue:145]: Let's not use [`toSpliced`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSpliced#browser_compatibility) yet.

Maybe let's do 
```suggestion
      modelValue.value = [...modelValue.value].splice(index, 1)
```

File: packages/radix-vue/src/TagsInput/TagsInputRoot.vue [hunk 2]
```diff
@@ -158,7 +158,7 @@ provideTagsInputRootContext({
 
         if (selectedElement.value) {
           const index = collection.findIndex(i => i === selectedElement.value)
-          modelValue.value.splice(index, 1)
+          modelValue.value = modelValue.value.toSpliced(index, 1)
```
Comment (zernonia) [inline packages/radix-vue/src/TagsInput/TagsInputRoot.vue:161]: same as above

**Comment by zernonia** [comment]
Thanks for the issue and PR @ploca14 !!! 🙏🏼 Some minor comment

**Review by zernonia — APPROVED** [review]

**Comment by zernonia** [comment]
there's seems to be some error with your code, also sorry for my bad suggestion, the line should be

```
- modelValue.value = [...modelValue.value].splice(index, 1)
+ modelValue.value = modelValue.value.filter((_, i) => i !== index)
```
